version: "3"

services:
        app:
                build: .
                depends_on:
                        - mongo
                ports:
                        - 3000:3000
                env_file:
                        - api.env.production
                environment:
                        - NODE_ENV=production
        mongo:
                image: mongo
                ports:
                        - 27017:27017               
