version: '3'

services:
  app:
    build: .
    depends_on:
      - mongo
    env_file:
      - .env.staging
    environment:
      - NODE_ENV=staging
      - PORT=8000
    ports:
      - 8000:8000
  mongo:
    image: mongo
    ports:
      - 27017:27017
